# Generated by Django 4.1.4 on 2022-12-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
